//Auth
export const AUTH_LOGIN_SUBMITTED = 'AUTH_LOGIN_SUBMITTED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUBMITTED = 'AUTH_LOGOUT_SUBMITTED';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';


// Async
export const LOADING_START = 'LOADING_START';
export const LOADING_START_RESET = 'LOADING_START_RESET';
export const LOADING_END = 'LOADING_END';
export const ASYNC_ERROR = 'ASYNC_ERROR';

//Common
export const REDUX_RESET = 'REDUX_RESET';

//Tasks
export const REQUEST_DEFAULT_TASKS = 'REQUEST_DEFAULT_TASKS';
export const REQUEST_TASK_BY_ID = 'REQUEST_TASK_BY_ID';
export const TASKS_RECEIVED = 'TASKS_RECEIVED';
export const REQUEST_TASKS_FROM_URL = 'REQUEST_TASKS_FROM_URL';
export const TASK_RECEIVED = 'TASK_RECEIVED';
export const TASK_UPDATED = 'TASK_UPDATED';
export const TASK_STATUS_UPDATED = 'TASK_STATUS_UPDATED';
export const TASK_UPLOADED = 'TASK_UPLOADED';

//System
export const REQUEST_FILTERS = 'REQUEST_FILTERS';
export const FILTERS_RECEIVED = 'FILTERS_RECEIVED';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SIDEBAR_IS_MINIFIED = 'SIDEBAR_IS_MINIFIED';
export const PROJECTS_RECEIVED = 'PROJECTS_RECEIVED';
export const OPTIONS_RECEIVED = 'OPTIONS_RECEIVED';

//settings
export const USERS_RECEIVED = 'USERS_RECEIVED';
export const REQUEST_USERS = 'REQUEST_USERS';
export const COMPANIES_RECEIVED = 'COMPANIES_RECEIVED';
export const REQUEST_COMPANIES = 'REQUEST_COMPANIES';
export const STATUSES_RECEIVED = 'STATUSES_RECEIVED';
export const REQUEST_STATUSES = 'REQUEST_STATUSES';
export const ROLES_RECEIVED = 'ROLES_RECEIVED';
export const REQUEST_ROLES = 'REQUEST_ROLES';
export const COMPANYATTRIBUTES_RECEIVED = 'COMPANYATTRIBUTES_RECEIVED';
export const COMPANYATTRIBUTE_RECEIVED = 'COMPANYATTRIBUTE_RECEIVED';
export const REQUEST_COMPANYATTRIBUTES = 'REQUEST_COMPANYATTRIBUTES';

export const TASKATTRIBUTES_RECEIVED = 'TASKATTRIBUTES_RECEIVED';
export const REQUEST_TASKATTRIBUTES = 'REQUEST_TASKATTRIBUTES';
export const IMAPS_RECEIVED = 'IMAPS_RECEIVED';
export const REQUEST_IMAPS = 'REQUEST_IMAPS';
export const SMTPS_RECEIVED = 'SMTPS_RECEIVED';
export const REQUEST_SMTPS = 'REQUEST_SMTPS';
export const PROJECTSHAREDFILTERS_RECEIVED = 'PROJECTSHAREDFILTERS_RECEIVED';
export const REQUEST_PROJECTSHAREDFILTERS = 'REQUEST_PROJECTSHAREDFILTERS';
export const SHAREDFILTERS_RECEIVED = 'SHAREDFILTERS_RECEIVED';
export const REQUEST_SHAREDFILTERS = 'REQUEST_SHAREDFILTERS';
export const UNITS_RECEIVED = 'UNITS_RECEIVED';
export const REQUEST_UNITS = 'REQUEST_UNITS';
export const USERATTRIBUTES_RECEIVED = 'USERATTRIBUTES_RECEIVED';
export const REQUEST_USERATTRIBUTES = 'REQUEST_USERATTRIBUTES';


//company
export const COMPANY_POST_NEW='COMPANY_POST_NEW';
export const COMPANY_CREATED='COMPANY_CREATED';
export const COMPANY_RECEIVED='COMPANY_RECEIVED';


//general
export const REQUEST_ENTITY='REQUEST_ENTITY';
export const PATCH_ENTITY='PATCH_ENTITY';
export const PUT_ENTITY='PUT_ENTITY';
export const CREATE_ENTITY='CREATE_ENTITY';
export const UPDATE_ENTITY='UPDATE_ENTITY';
export const DELETE_ENTITY='DELETE_ENTITY';